---
title: "Robust meta-analysis and meta-regression"
author: 
  - name: Joon-Ho Lee (joonho@berkeley.edu)
date: "February 29, 2020"
output:
  html_document: 
    css: styles.css
    fig_caption: yes
    highlight: haddock
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
  tufte::tufte_html:
    number_sections: yes
    toc: true
    toc_depth: 2
  pdf_document:
    toc: yes
    toc_depth: '3'
bibliography: bibliography.bib
---

```{r basic_setup, include=FALSE}
### Set working directory
setwd("~/meta-analysis/03_metaplus")

### Set RMarkdown options
knitr::opts_chunk$set(echo = TRUE, warnings = FALSE, message = FALSE)

### Call libraries
library(tidyverse)
library(cowplot)
library(DPpackage)
library(bspmma)
library(metaplus)

# ### Set Stan options
# # options(mc.cores = parallel::detectCores())
# rstan_options(auto_write = TRUE)
# Sys.setenv(LOCAL_CPPFLAGS = '-march=native')

### Theme settings
theme_preset <- 
  theme_bw() + 
  theme(panel.background = element_blank(),
        panel.grid = element_blank(), 
        legend.position = "bottom", 
        legend.direction = "horizontal", 
        legend.title = element_blank())
```


```{r}
# perform meta-analysis for mag studies, which have no outliers
# fit standard normal random-effect model and print summary
mag.meta <- metaplus(yi, sei, slab = study, data = mag)
summary(mag.meta)

# repeat, but this time plot the profile likelihood diagnostic plot using plotci
mag.meta <- metaplus(mag$yi, mag$sei, slab = mag$study, plotci = TRUE)

# plot a forest plot with exponential transform, so that the odds ratios are plotted
plot(mag.meta, atransf = exp, at = log(c(.01, .1, 1, 10, 100)), xlab = "Odds Ratio", cex = 0.75)

# repeat for t-distribution random effects
mag.tdist <- metaplus(yi, sei, slab = study, random = "t-dist", data = mag)
summary(mag.tdist)

# use parametric bootstrap to test for presence of outliers
summary(testOutliers(mag.tdist))

# repeat for robust mixture random effects
mag.mix <- metaplus(yi, sei, slab = study, random = "mixture", data = mag)
summary(mag.mix)

# use parametric bootstrap to test for presence of outliers
summary(testOutliers(mag.mix))

# perform meta-analysis for CDP studies
# where there is one outlier
cdp.meta <- metaplus(yi, sei, slab = study, data = cdp)
summary(cdp.meta)
cdp.tdist <- metaplus(yi, sei, slab = study,
random = "t-dist", data = cdp)
summary(cdp.tdist)
summary(testOutliers(cdp.tdist))
cdp.mix <- metaplus(yi, sei, slab = study,
random = "mixture", data = cdp)
summary(cdp.mix)
summary(testOutliers(cdp.mix))

# extract and plot outlier probabilities
cdp.mix.outlierProbs <- outlierProbs(cdp.mix)
plot(cdp.mix.outlierProbs)
# produce forest plot with summary for all 3 models, showing narrower confidence
# intervals for robust models
plot(cdp.meta, extrameta = list(cdp.tdist, cdp.mix), xlab = "Standardised Mean Difference")
# effect of exercise on depression with covariate of length of study
# fit the 3 models
exercise.meta <- metaplus(smd, sqrt(varsmd),
mods = duration, slab = study, data = exercise)
summary(exercise.meta)
exercise.mix <- metaplus(smd, sqrt(varsmd),
mods = duration, slab = study, random = "mixture",
data = exercise)
summary(exercise.mix)
exercise.testOutliers <- testOutliers(exercise.mix)
summary(exercise.testOutliers)
# identify possible outliers
exercise.outlierProbs <- outlierProbs(exercise.mix)
plot(exercise.outlierProbs)
# centre duration at different values to obtain predictions at 4, 8 and 12 weeks
exercise$duration4 <- exercise$duration-4
exercise$duration8 <- exercise$duration-8
exercise$duration12 <- exercise$duration-12
# fit the different models, giving each an appropriate label
exercise.nodurn <- metaplus(smd, sqrt(varsmd),
label = "Random Mixture (No Duration)", slab = study,
random = "mixture", data = exercise)
exercise.wk4 <- metaplus(smd, sqrt(varsmd),
mods = duration4, label = "Random Mixture (Week 4)",
slab = study, random = "mixture", data = exercise)
exercise.wk8 <- metaplus(smd, sqrt(varsmd),
mods = duration8, label = "Random Mixture (Week 8)",
slab = study, random = "mixture", data = exercise)
exercise.wk12 <- metaplus(smd, sqrt(varsmd),
mods = duration12, label = "Random Mixture (Week 12)",
slab = study, random = "mixture", data = exercise)
# produce forest plot with summary for each model with robust mixture model at different weeks
plot(exercise.nodurn, extrameta = list(exercise.wk4, exercise.wk8,
exercise.wk12), xlab = "Standardised mean difference")

```



# References



